language: node_js

node_js:
  - 0.10
  - 4

services:
  - redis

before_script:
  - redis-server --port 6378 --requirepass secret &
  - redis-server --port 6377 --unixsocket /tmp/redis.sock &
  - sleep 2
